/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_matrixlab_webp4j_internal_NativeWebP */

#ifndef _Included_dev_matrixlab_webp4j_internal_NativeWebP
#define _Included_dev_matrixlab_webp4j_internal_NativeWebP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    getLibWebPVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_getLibWebPVersion
  (JNIEnv *, jclass);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    getInfo
 * Signature: ([B[I)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_getInfo
  (JNIEnv *, jclass, jbyteArray, jintArray);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    getFeatures
 * Signature: ([BILdev/matrixlab/webp4j/model/WebPBitstreamFeatures;)I
 */
JNIEXPORT jint JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_getFeatures
  (JNIEnv *, jclass, jbyteArray, jint, jobject);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    encode
 * Signature: ([IIIFZZZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_encode
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jboolean, jboolean, jboolean);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    encodeBgr
 * Signature: ([BIIFZZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_encodeBgr
  (JNIEnv *, jclass, jbyteArray, jint, jint, jfloat, jboolean, jboolean);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    decodeInto
 * Signature: ([B[II)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_decodeInto
  (JNIEnv *, jclass, jbyteArray, jintArray, jint);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    getGifInfo
 * Signature: ([BLdev/matrixlab/webp4j/model/AnimationInfo;)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_getGifInfo
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    encodeGifToWebP
 * Signature: ([BFZIZIIIZZZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_encodeGifToWebP
  (JNIEnv *, jclass, jbyteArray, jfloat, jboolean, jint, jboolean, jint, jint, jint, jboolean, jboolean, jboolean);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    encodeAnimated
 * Signature: ([[I[IIIFZIIIIZZZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_encodeAnimated
  (JNIEnv *, jclass, jobjectArray, jintArray, jint, jint, jfloat, jboolean, jint, jint, jint, jint, jboolean, jboolean, jboolean);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    decodeAnimated
 * Signature: ([BLdev/matrixlab/webp4j/model/AnimatedWebPData;)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_decodeAnimated
  (JNIEnv *, jclass, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
