/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_matrixlab_webp4j_internal_NativeWebP */

#ifndef _Included_dev_matrixlab_webp4j_internal_NativeWebP
#define _Included_dev_matrixlab_webp4j_internal_NativeWebP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    getLibWebPVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_getLibWebPVersion
  (JNIEnv *, jclass);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    getInfo
 * Signature: ([B[I)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_getInfo
  (JNIEnv *, jclass, jbyteArray, jintArray);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    getFeatures
 * Signature: ([BILdev/matrixlab/webp4j/model/WebPBitstreamFeatures;)I
 */
JNIEXPORT jint JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_getFeatures
  (JNIEnv *, jclass, jbyteArray, jint, jobject);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    encodeRGB
 * Signature: ([BIIIF)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_encodeRGB
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jfloat);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    encodeRGBA
 * Signature: ([BIIIF)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_encodeRGBA
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jfloat);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    encodeLosslessRGB
 * Signature: ([BIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_encodeLosslessRGB
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    encodeLosslessRGBA
 * Signature: ([BIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_encodeLosslessRGBA
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    decodeRGBInto
 * Signature: ([B[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_decodeRGBInto
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    decodeRGBAInto
 * Signature: ([B[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_decodeRGBAInto
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    getGifInfo
 * Signature: ([BLdev/matrixlab/webp4j/model/AnimationInfo;)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_getGifInfo
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    encodeGifToWebP
 * Signature: ([BFZIZIIIZZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_encodeGifToWebP
  (JNIEnv *, jclass, jbyteArray, jfloat, jboolean, jint, jboolean, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    encodeAnimatedWebP
 * Signature: ([[B[IIIFZIIIIZZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_encodeAnimatedWebP
  (JNIEnv *, jclass, jobjectArray, jintArray, jint, jint, jfloat, jboolean, jint, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     dev_matrixlab_webp4j_internal_NativeWebP
 * Method:    decodeAnimatedWebP
 * Signature: ([BLdev/matrixlab/webp4j/model/AnimatedWebPData;)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_matrixlab_webp4j_internal_NativeWebP_decodeAnimatedWebP
  (JNIEnv *, jclass, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
